version: "3"

services:
  backend:
    container_name: koors_backend
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - web
      - internal
    environment:
      - PORT=4000
    volumes:
      - ./back/persist:/app/persist
      - ./back/persist-save:/app/persist-save

  nginx:
    container_name: nginx_babbel
    image: nginx
    restart: unless-stopped
    networks:
      - web
      - internal
    volumes:
      - ./build:/etc/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    labels:
      - traefik.enable=true
      - traefik.backend=nginx_babbel
      - traefik.docker.network=web
      # Port
      - traefik.http.services.nginx_babbel.loadBalancer.server.port=80

      # Rule
      - traefik.http.routers.nginx_babbel.rule=Host(`babbel.jehanno.net`)
      # SSL configuration
      - traefik.http.routers.nginx_babbel.entryPoints=websecure
      - traefik.http.routers.nginx_babbel.tls=true
      - traefik.http.routers.nginx_babbel.tls.certResolver=myresolver

networks:
  web:
    external: true
  internal:
    driver: bridge
