export const defaultIngredientsToValidate = [
  "curcuma",
  "cumin",
  "bouillon cube",
  "noix de muscade",
  "épice chili",
  "origan",
  "ail",
  "oignon",
  "échalote",
  "oeuf",
  "farine 100g",
  "farine d'épeautre",
  "levure",
  "fromage rapé",
  "lait",
  "parmesan",
  "curry",
  "huile de coco",
  "sucre",
  "sucre brun",
  "sucre vanillé",
  "paprika",
  "ras-el-hanout",
  "harissa",
  "coriandre",
  "sauce soja",
  "nuoc mam",
  "galette de riz",
  "semoule 200g",
  "pomme de terre",
  "beurre",
  "rhum",
  "nutella",
  "lentille",
  "riz",
  "agar-agar",
  "herbes de provence",
  "ketchup",
  "moutarde",
];

export const defaultCategoryMap: { [key: string]: string } = {
  oignon: "fruits-et-légumes",
  "oignon rouge": "fruits-et-légumes",
  ail: "fruits-et-légumes",
  échalote: "fruits-et-légumes",
  gingembre: "fruits-et-légumes",
  "épinards frais": "fruits-et-légumes",
  tomate: "fruits-et-légumes",
  fruits: "fruits-et-légumes",
  carotte: "fruits-et-légumes",
  poivron: "fruits-et-légumes",
  courgette: "fruits-et-légumes",
  aubergine: "fruits-et-légumes",
  "choux-fleur": "fruits-et-légumes",
  "patate douce": "fruits-et-légumes",
  "courge butternut": "fruits-et-légumes",
  "piment vert": "fruits-et-légumes",
  "citron vert": "fruits-et-légumes",
  citron: "fruits-et-légumes",
  pomme: "fruits-et-légumes",
  "choux rouge": "fruits-et-légumes",
  choux: "fruits-et-légumes",
  coriandre: "fruits-et-légumes",
  salade: "fruits-et-légumes",
  avocat: "fruits-et-légumes",
  menthe: "fruits-et-légumes",
  "pomme de terre": "fruits-et-légumes",
  champignon: "fruits-et-légumes",
  poireau: "fruits-et-légumes",
  curcuma: "épices",
  curry: "épices",
  cumin: "épices",
  "bouillon cube": "épices",
  "noix de muscade": "épices",
  sel: "épices",
  poivre: "épices",
  "épice chili": "épices",
  paprika: "épices",
  "ras-el-hanout": "épices",
  harissa: "épices",
  origan: "épices",
  "épices chili": "épices",
  skir: "laitages",
  féta: "laitages",
  mozzarella: "laitages",
  "cottage cheese 250g": "laitages",
  "gorgonzola 100g": "laitages",
  beurre: "laitages",
  oeuf: "laitages",
  "fromage rapé": "laitages",
  parmesan: "laitages",
  "crème fraiche": "laitages",
  "pois chiche 300g": "conserves",
  mais: "conserves",
  "concassé tomate 50cl": "conserves",
  "haricot rouge 300g": "conserves",
  "concentré de tomate": "conserves",
  "coulis de tomate 200g": "conserves",
  "lentille corail 200g": "sauce-feculent",
  "semoule 200g": "sauce-feculent",
  lentille: "sauce-feculent",
  "pates courtes 250g": "sauce-feculent",
  "pates longues 250g": "sauce-feculent",
  "conchiglionis 300g": "sauce-feculent",
  lasagne: "sauce-feculent",
  "huile d'olive": "sauce-feculent",
  vinaigre: "sauce-feculent",
  cornichons: "sauce-feculent",
  ketchup: "sauce-feculent",
  "riz à risotto": "sauce-feculent",
  "tomate séchée": "sauce-feculent",
  "coeur d'artichaut": "sauce-feculent",
  riz: "sauce-feculent",
  pq: "hygiène",
  dentrifice: "hygiène",
  "tablettes lave vaisselle": "hygiène",
  "liquide rincage": "hygiène",
  lessive: "hygiène",
  tampon: "hygiène",
  savon: "hygiène",
  "sac poubelle": "hygiène",
  "épinard surgelé 500g": "surgelés",
  "légume du soleil surgelé": "surgelés",
  "chips tortillas": "apéro",
  sirop: "apéro",
  lait: "apéro",
  rhum: "apéro",
  "farine 100g": "ingredient-cuisine",
  "farine d'épeautre": "ingredient-cuisine",
  sucre: "ingredient-cuisine",
  "sucre brun": "ingredient-cuisine",
  "sucre vanillé": "ingredient-cuisine",
  levure: "ingredient-cuisine",
  "pignons de pain": "ingredient-cuisine",
  noix: "ingredient-cuisine",
  "noix de cajou": "ingredient-cuisine",
  "abricots sec": "ingredient-cuisine",
  amandes: "ingredient-cuisine",
  graines: "ingredient-cuisine",
  chocolat: "ingredient-cuisine",
  "chocolat cuisine": "ingredient-cuisine",
  "lait de coco gras 400ml": "cuisine-du-monde",
  "lait de coco": "cuisine-du-monde",
  "huile de coco": "cuisine-du-monde",
  "vermicelle de riz": "cuisine-du-monde",
  "galette de riz": "cuisine-du-monde",
  "pousse de soja": "cuisine-du-monde",
  "sauce soja": "cuisine-du-monde",
  "nuoc mam": "cuisine-du-monde",
  "vinaigre de riz": "cuisine-du-monde",
  galette: "000-none",
  "pate feuilleté": "000-none",
  "allumettes de bacon": "000-none",
  chorizo: "000-none",
  jambon: "000-none",
  "pain à burger": "000-none",
  café: "000-none",
  chapelure: "000-none",
  "compote de pomme": "000-none",
  nutella: "000-none",
  "pain de mis": "000-none",
  "tomate cerise": "fruits-et-légumes",
  wrap: "cuisine-du-monde",
  halloumi: "laitages",
  roquette: "fruits-et-légumes",
  houmous: "000-none",
  "gateau sablé": "ingredient-cuisine",
  "noix de coco rapée": "ingredient-cuisine",
  "fromage blanc": "laitages",
  "agar-agar": "ingredient-cuisine",
  "crème de coco": "ingredient-cuisine",
  "liquide vaisselle": "hygiène",
  "savon liquide": "hygiène",
  "skyr nature": "laitages",
  banane: "fruits-et-légumes",
  burrata: "laitages",
  "coton tige": "hygiène",
  ravioli: "000-none",
  mouchoirs: "hygiène",
  brocoli: "fruits-et-légumes",
  fromage: "laitages",
  "knacki végé": "000-none",
  endive: "fruits-et-légumes",
  éponge: "hygiène",
  "légume asiatique surgelé": "surgelés",
  concombre: "fruits-et-légumes",
  radis: "fruits-et-légumes",
  yaourt: "laitages",
  "petit pois surgelé": "surgelés",
  "vinaigre blanc": "conserves",
  "herbes de provence": "épices",
  chèvre: "laitages",
  figue: "fruits-et-légumes",
  "sauce tomate": "fruits-et-légumes",
  moutarde: "épices",
  "steak végé": "000-none",
  bière: "apéro",
  ciboulette: "fruits-et-légumes",
  mayonnaise: "sauce-feculent",
  gateaux: "ingredient-cuisine",
  champoing: "hygiène",
  boursin: "laitages",
  grenade: "fruits-et-légumes",
  "madame loic": "laitages",
  "piment rouge": "fruits-et-légumes",
  "céréales b12": "000-none",
  skyr: "laitages",
  pain: "000-none",
  tofu: "cuisine-du-monde",
  kiri: "laitages",
  quinoa: "sauce-feculent",
  jus: "apéro",
  melon: "fruits-et-légumes",
};

export const defaultRecettes = [
  {
    name: "beurre",
    type: "singleItem",
    ingredients: {
      beurre: 1,
    },
  },
  {
    name: "café",
    type: "singleItem",
    ingredients: {
      café: 1,
    },
  },
  {
    name: "chocolat",
    type: "singleItem",
    ingredients: {
      beurre: 1,
    },
  },
  {
    name: "dentrifice",
    type: "singleItem",
    ingredients: {
      dentrifice: 1,
    },
  },
  {
    name: "fruits",
    type: "singleItem",
    ingredients: {
      fruits: 1,
    },
  },
  {
    name: "huile d'olive",
    type: "singleItem",
    ingredients: {
      "huile d'olive": 1,
    },
  },
  {
    name: "lessive",
    type: "singleItem",
    ingredients: {
      lessive: 1,
    },
  },
  {
    name: "liquide rincage",
    type: "singleItem",
    ingredients: {
      "liquide rincage": 1,
    },
  },
  {
    name: "mouchoirs",
    type: "singleItem",
    ingredients: {
      mouchoirs: 1,
    },
  },
  {
    name: "poivre",
    type: "singleItem",
    ingredients: {
      poivre: 1,
    },
  },
  {
    name: "PQ",
    type: "singleItem",
    ingredients: {
      pq: 1,
    },
  },
  {
    name: "sel",
    type: "singleItem",
    ingredients: {
      sel: 1,
    },
  },
  {
    name: "sirop",
    type: "singleItem",
    ingredients: {
      sirop: 1,
    },
  },
  {
    name: "tablettes lave vaisselle",
    type: "singleItem",
    ingredients: {
      "tablettes lave vaisselle": 1,
    },
  },
  {
    name: "tampon",
    type: "singleItem",
    ingredients: {
      tampon: 1,
    },
  },
  {
    name: "vinaigre",
    type: "singleItem",
    ingredients: {
      vinaigre: 1,
    },
  },
  {
    name: "Burito haricot rouge",
    ingredients: {
      oignon: 1,
      courgette: 1,
      carotte: 1,
      "épice chili": 1,
      "concassé tomate 50cl": 8,
      "haricot rouge 300g": 1,
      wrap: 1,
      lentille: 1,
      ciboulette: 1,
      avocat: 1,
      citron: 1,
      "fromage rapé": 1,
    },
    type: "flemme",
    link: "https://www.notion.so/dekajoo/Burrito-Miam-Miam-haricot-rouge-aa1262d92bcc4f58a31b782a910e5dab",
    personnes: 3,
  },
  {
    name: "Croques monsieur",
    ingredients: {
      "pain de mis": 1,
      jambon: 1,
      "crème fraiche": 1,
      "fromage rapé": 1,
      salade: 1,
    },
    type: "flemme",
    personnes: 4,
  },
  {
    name: "Pates carbo",
    ingredients: {
      "allumettes de bacon": 1,
      oeuf: 2,
      "crème fraiche": 1,
      "pates longues 250g": 1,
    },
    type: "flemme",
    personnes: 4,
  },
  {
    name: "poivrons et feta roti",
    ingredients: {
      poivron: 2,
      féta: 1,
      "herbes de provence": 1,
    },
    type: "flemme",
    link: "https://www.notion.so/dekajoo/Poivron-et-feta-roti-6d51a962612f441392b5294c726f790d",
    personnes: 2,
  },
  {
    name: "Pâtes aux oignons rouges & gorgonzola",
    ingredients: {
      "pates courtes 250g": 1,
      "oignon rouge": 3,
      "gorgonzola 100g": 1,
      noix: 1,
    },
    type: "flemme",
    link: "https://owiowifouettemoi.com/2019/05/21/farniente-pasta/",
    personnes: 2,
  },
  {
    name: "Quiche aux légumes",
    ingredients: {
      "légume du soleil surgelé": 1,
      "crème fraiche": 1,
      "pate feuilleté": 1,
      oeuf: 3,
      lait: 1,
      féta: 1,
    },
    type: "flemme",
    personnes: 4,
  },
  {
    name: "Quiche aux épinards",
    ingredients: {
      "épinard surgelé 500g": 1,
      "crème fraiche": 1,
      "pate feuilleté": 1,
      oeuf: 3,
      lait: 1,
      féta: 1,
    },
    type: "flemme",
    personnes: 4,
  },
  {
    name: "Salade de lentille",
    ingredients: {
      lentille: 1,
      féta: 1,
      pomme: 1,
      "choux rouge": 1,
    },
    type: "flemme",
  },
  {
    name: "spaghetti tomates balsamique burrata",
    ingredients: {
      "tomate cerise": 12,
      vinaigre: 1,
      burrata: 1,
      "pates longues 250g": 2,
    },
    type: "flemme",
    link: "https://www.notion.so/dekajoo/spaghetti-aux-tomates-balsamique-burrata-7c9d11e81711488fb4bddeff07960cc9",
    personnes: 2,
  },
  {
    name: "Tarte tatin à la tomate",
    ingredients: {
      tomate: 7,
      "pignons de pain": 1,
      "pate feuilleté": 1,
      vinaigre: 1,
    },
    type: "flemme",
    link: "https://dekajoo.notion.site/Tarte-tatin-tomates-44bca60e13474c1ca08789eef22ac632",
    personnes: 4,
  },
  {
    name: "Wrap à la libanaise",
    ingredients: {
      wrap: 1,
      houmous: 1,
      "tomate cerise": 1,
      roquette: 1,
      halloumi: 1,
    },
    type: "flemme",
    link: "https://dekajoo.notion.site/Wrap-la-libanaise-8a3ba2e1eed44033bccebc4202969170",
    personnes: 2,
  },
  {
    name: "Cheese cake coco citron",
    ingredients: {
      "crème de coco": 1,
      "gateau sablé": 1,
      beurre: 1,
      "noix de coco rapée": 1,
      "fromage blanc": 1,
      sucre: 1,
      "sucre vanillé": 1,
      "agar-agar": 1,
      oeuf: 2,
      "citron vert": 1,
    },
    type: "dessert",
    link: "http://www.les-mets-tisses.com/2012/11/cheesecake-coco-citron-vert-sans-cuisson.html?m=1",
    personnes: 6,
  },
  {
    name: "Cookies",
    ingredients: {
      beurre: 1,
      "sucre brun": 1,
      sucre: 1,
      oeuf: 1,
      "sucre vanillé": 1,
      "farine 100g": 2,
      levure: 1,
      "chocolat cuisine": 1,
      amandes: 1,
    },
    link: "https://dekajoo.notion.site/Cookies-54fdd89445744a8abfb396c825be235a",
    personnes: 4,
    type: "dessert",
  },
  {
    name: "Crèpes sucrées",
    ingredients: {
      "farine 100g": 3,
      oeuf: 4,
      lait: 1,
      beurre: 1,
      rhum: 1,
      sucre: 1,
      nutella: 1,
      citron: 1,
    },
    link: "https://cuisine.journaldesfemmes.fr/recette/333415-recette-de-crepes-la-meilleure-recette-rapide",
    personnes: 4,
    type: "dessert",
  },
  {
    name: "Gateau léger à la compote",
    ingredients: {
      "compote de pomme": 1,
      "huile de coco": 1,
      oeuf: 2,
      sucre: 1,
      "farine d'épeautre": 1,
      levure: 1,
    },
    type: "dessert",
    personnes: 4,
  },
  {
    name: "Burger végé féta",
    ingredients: {
      féta: 1,
      oeuf: 1,
      "farine 100g": 1,
      graines: 1,
      cumin: 1,
      "pain à burger": 2,
      cornichons: 1,
      ketchup: 1,
    },
    link: "https://dekajoo.notion.site/Steak-feta-cfe2ad9e8ccf4795b9d9da830bc61b0a",
  },
  {
    name: "Chili végé",
    ingredients: {
      oignon: 3,
      carotte: 3,
      poivron: 3,
      "haricot rouge 300g": 2,
      "pois chiche 300g": 1,
      "épices chili": 1,
      cumin: 1,
      "bouillon cube": 1,
      "concassé tomate 50cl": 2,
      "chips tortillas": 1,
    },
    link: "https://dekajoo.notion.site/Chili-v-g-d9e25dc8dda84df39f841c252434b6d6",
    personnes: 6,
  },
  {
    name: "Conchiglionis farcis, brousse-épinard",
    ingredients: {
      "conchiglionis 300g": 1,
      "épinard surgelé 500g": 1,
      "cottage cheese 250g": 1,
      "concassé tomate 50cl": 1,
      chapelure: 1,
      "noix de muscade": 1,
    },
    link: "https://dekajoo.notion.site/Conchiglionis-farcis-brousse-pinard-c8e5fbbca7384fc99b149f1c24cd6036",
  },
  {
    name: "Couscous végé",
    ingredients: {
      "semoule 200g": 3,
      "oignon rouge": 2,
      tomate: 4,
      courgette: 4,
      carotte: 4,
      "pomme de terre": 3,
      "piment vert": 2,
      choux: 1,
      "pois chiche 300g": 1,
      "concentré de tomate": 1,
      paprika: 1,
      "ras-el-hanout": 1,
      "bouillon cube": 1,
      harissa: 1,
      amandes: 1,
      coriandre: 1,
    },
    personnes: 6,
  },
  {
    name: "Crèpes aux champis",
    ingredients: {
      galette: 4,
      champignon: 1,
      oignon: 1,
      "crème fraiche": 1,
      "fromage rapé": 1,
      oeuf: 4,
      salade: 1,
    },
    personnes: 4,
  },
  {
    name: "Curry patate douce lentilles",
    personnes: 4,
    ingredients: {
      lentille: 1,
      ail: 1,
      échalote: 1,
      oignon: 1,
      gingembre: 1,
      "huile d'olive": 1,
      "lait de coco": 1,
      "patate douce": 2,
      "noix de cajou": 1,
      salade: 1,
      riz: 1,
    },
    link: "https://dekajoo.notion.site/Curry-de-patate-douce-e8a2fee688b14c07b8f1d8eff98a201c",
  },
  {
    name: "Curry sri-lankais",
    ingredients: {
      curry: 1,
      "patate douce": 1,
      "courge butternut": 1,
      poivron: 2,
      "oignon rouge": 2,
      ail: 3,
      "piment vert": 2,
      "épinards frais": 1,
      "citron vert": 1,
      curcuma: 1,
      riz: 1,
    },
    personnes: 4,
  },
  {
    name: "Dhal de choux-fleur et de lentille corail",
    ingredients: {
      "choux-fleur": 1,
      "lentille corail 200g": 1,
      "lait de coco gras 400ml": 2,
      "abricots sec": 1,
      curry: 1,
      ail: 2,
      carotte: 2,
      oignon: 1,
      "huile de coco": 1,
      riz: 1,
    },
    personnes: 4,
  },
  {
    name: "Gauffre à la patate douce",
    ingredients: {
      "patate douce": 1,
      oeuf: 3,
      "farine 100g": 2,
      lait: 1,
      "fromage rapé": 1,
    },
    personnes: 4,
  },
  {
    name: "Lasagnes aux légumes du soleil",
    ingredients: {
      lasagne: 1,
      oignon: 2,
      courgette: 3,
      poivron: 3,
      aubergine: 1,
      tomate: 3,
      "coulis de tomate 200g": 1,
      "fromage rapé": 1,
      lait: 1,
      beurre: 1,
      "noix de muscade": 1,
    },
    personnes: 4,
    link: "https://www.marmiton.org/recettes/recette_lasagnes-vegetariennes-facile_10527.aspx",
  },
  {
    name: "Lasagnes aux épinards",
    ingredients: {
      lasagne: 1,
      "épinard surgelé 500g": 2,
      "cottage cheese 250g": 2,
      lait: 1,
    },
    personnes: 4,
  },
  {
    name: "Lentilles yaourt aubergine",
    ingredients: {
      aubergine: 4,
      lentille: 1,
      yaourt: 1,
      "tomate cerise": 24,
      citron: 1,
      ail: 1,
      origan: 1,
    },
    type: "default",
    link: "https://www.notion.so/dekajoo/Lentille-caviar-d-aubergine-8a35837eac8547109a131144ba075c60",
    personnes: 4,
  },
  {
    name: "Pho",
    ingredients: {
      "bouillon cube": 1,
      poireau: 2,
      champignon: 1,
      "sauce soja": 1,
      "nuoc mam": 1,
      gingembre: 1,
      "piment vert": 1,
      ail: 1,
      oignon: 1,
    },
    personnes: 2,
    link: "https://www.notion.so/dekajoo/Pho-e8ca0efeeeeb436bb28028c32aee8a29",
  },
  {
    name: "Pierogi (entrée)",
    ingredients: {
      "farine 100g": 3,
      oeuf: 3,
      "cottage cheese 250g": 1,
      beurre: 1,
    },
    link: "https://dekajoo.notion.site/Pierogi-54ec793bc45846808bf84f1e5968573d",
    personnes: 4,
  },
  {
    name: "Pizza",
    ingredients: {
      champignon: 1,
      oignon: 1,
      chorizo: 1,
      mozzarella: 1,
      "concassé tomate 50cl": 1,
      origan: 1,
      salade: 1,
      "coeur d'artichaut": 1,
      "farine 100g": 1,
      levure: 1,
    },
    personnes: 4,
  },
  {
    name: "Ratatouille",
    ingredients: {
      poivron: 3,
      oignon: 2,
      aubergine: 2,
      courgette: 4,
      ail: 1,
      riz: 1,
    },
    type: "default",
    link: "",
    personnes: 4,
  },
  {
    name: "Risotto aux champignons & tomates séchées",
    ingredients: {
      champignon: 1,
      oignon: 1,
      "tomate séchée": 1,
      "riz à risotto": 1,
      "bouillon cube": 1,
      parmesan: 1,
      salade: 1,
    },
    personnes: 4,
  },
  {
    name: "Rouleaux de printemps",
    ingredients: {
      salade: 1,
      carotte: 1,
      avocat: 1,
      "citron vert": 1,
      "vermicelle de riz": 1,
      "galette de riz": 8,
      menthe: 1,
      "pousse de soja": 1,
      "sauce soja": 1,
      "vinaigre de riz": 1,
    },
    personnes: 4,
  },
  {
    name: "Stew",
    ingredients: {
      oignon: 1,
      ail: 5,
      gingembre: 1,
      curcuma: 1,
      "pois chiche 300g": 2,
      "lait de coco gras 400ml": 1,
      "bouillon cube": 1,
      "épinards frais": 1,
      skir: 1,
      tomate: 2,
      échalote: 2,
      riz: 1,
    },
    link: "https://owiowifouettemoi.com/2019/01/23/the-stew-pois-chiche-coco-et-curcuma/",
  },
  {
    name: "Lentilles corail à la greque",
    ingredients: {
      "lentille corail 200g": 2,
      féta: 1,
      "sauce tomate": 1,
      "herbes de provence": 1,
    },
    type: "flemme",
    link: "",
    personnes: 4,
  },
];
